### ISSUE TITLE
TODO 2024/10/11

### ISSUE THREAD

**Issue by ZebraAlgebra** [ZebraAlgebra/convex-analysis-notes#2]
- [x] Proofread chapter 3, 4.
- [x] Add contents on directional derivatives, subgradients.
- [x] Expand and refactor section 2.6 (on polyhedral functions).
- [x] Add contents to section 4.6 (on subgradients).
- [x] Add notation for differentiability clases in preface.

**Comment by ZebraAlgebra** [comment]
done.
