### ISSUE TITLE
TODO 2024/10/22

### ISSUE THREAD

**Issue by ZebraAlgebra** [ZebraAlgebra/convex-analysis-notes#4]
- [x] Add contents on minimax. These are still kind of important.
- [ ] (Possibly not) Add contents on theorems of alternatives.
- [ ] (Possibly not) Add selected exercises from the book.
